[package]
name = "rwa-factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
linera-sdk.workspace = true
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
anyhow.workspace = true